language: python
python:
  - "3.5"
  - "3.6"


addons:
  apt:
    packages:
      - graphviz
      - git


install:
  - sudo apt-get install graphviz
  - sudo apt-get install git
  - python setup.py install


script:
  - pytest tests