language: python
python:
  - "3.6"


addons:
  apt:
    packages:
      - graphviz
      - git


# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get install graphviz
  - sudo apt-get install git
  - python setup.py install


# command to run tests
script:
  - pytest tests